site_name: Nmap Script Tutorial
site_url: https://tristan-white.github.io/nmap-script-tutorial/
# repo_url: https://github.com/tristan-white/nmap-script-tutorial
# repo_name: tristan-white/nmap-script-tutorial
theme:
  name: material
  icon:
    logo: material/eye
  palette: 
    scheme: slate
    primary: deep purple
  features:
    # - navigation.tabs
    - content.code.copy
plugins:
  - termynal:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
nav:
  - Home: index.md
  - Getting Started: getting-started.md
extra:
  analytics:
    provider: google
    property: G-T9WQVFX98N 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tristan-white
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tr15t4n/
    - icon: fontawesome/solid/circle-info
      link: https://tristanwhite.me